// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: customer.proto

package pr.iceworld.fernando.protobuf.proto;

public final class CustomerProto {
  private CustomerProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code pr.iceworld.fernando.protobuf.proto.Gender}
   */
  public enum Gender
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>MALE = 0;</code>
     */
    MALE(0),
    /**
     * <code>FEMALE = 1;</code>
     */
    FEMALE(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>MALE = 0;</code>
     */
    public static final int MALE_VALUE = 0;
    /**
     * <code>FEMALE = 1;</code>
     */
    public static final int FEMALE_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Gender valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Gender forNumber(int value) {
      switch (value) {
        case 0: return MALE;
        case 1: return FEMALE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Gender>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Gender> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Gender>() {
            public Gender findValueByNumber(int number) {
              return Gender.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return pr.iceworld.fernando.protobuf.proto.CustomerProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final Gender[] VALUES = values();

    public static Gender valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Gender(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:pr.iceworld.fernando.protobuf.proto.Gender)
  }

  public interface CustomerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pr.iceworld.fernando.protobuf.proto.Customer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     * enum type
     * </pre>
     *
     * <code>.pr.iceworld.fernando.protobuf.proto.Gender gender = 3;</code>
     * @return The enum numeric value on the wire for gender.
     */
    int getGenderValue();
    /**
     * <pre>
     * enum type
     * </pre>
     *
     * <code>.pr.iceworld.fernando.protobuf.proto.Gender gender = 3;</code>
     * @return The gender.
     */
    pr.iceworld.fernando.protobuf.proto.CustomerProto.Gender getGender();

    /**
     * <pre>
     * array
     * </pre>
     *
     * <code>repeated .pr.iceworld.fernando.protobuf.proto.Customer.Address addresses = 4;</code>
     */
    java.util.List<pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.Address> 
        getAddressesList();
    /**
     * <pre>
     * array
     * </pre>
     *
     * <code>repeated .pr.iceworld.fernando.protobuf.proto.Customer.Address addresses = 4;</code>
     */
    pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.Address getAddresses(int index);
    /**
     * <pre>
     * array
     * </pre>
     *
     * <code>repeated .pr.iceworld.fernando.protobuf.proto.Customer.Address addresses = 4;</code>
     */
    int getAddressesCount();
    /**
     * <pre>
     * array
     * </pre>
     *
     * <code>repeated .pr.iceworld.fernando.protobuf.proto.Customer.Address addresses = 4;</code>
     */
    java.util.List<? extends pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.AddressOrBuilder> 
        getAddressesOrBuilderList();
    /**
     * <pre>
     * array
     * </pre>
     *
     * <code>repeated .pr.iceworld.fernando.protobuf.proto.Customer.Address addresses = 4;</code>
     */
    pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.AddressOrBuilder getAddressesOrBuilder(
        int index);

    /**
     * <code>.pr.iceworld.fernando.protobuf.proto.Phone phone = 5;</code>
     * @return Whether the phone field is set.
     */
    boolean hasPhone();
    /**
     * <code>.pr.iceworld.fernando.protobuf.proto.Phone phone = 5;</code>
     * @return The phone.
     */
    pr.iceworld.fernando.protobuf.proto.PhoneProto.Phone getPhone();
    /**
     * <code>.pr.iceworld.fernando.protobuf.proto.Phone phone = 5;</code>
     */
    pr.iceworld.fernando.protobuf.proto.PhoneProto.PhoneOrBuilder getPhoneOrBuilder();

    /**
     * <code>map&lt;string, string&gt; attrs = 6;</code>
     */
    int getAttrsCount();
    /**
     * <code>map&lt;string, string&gt; attrs = 6;</code>
     */
    boolean containsAttrs(
        java.lang.String key);
    /**
     * Use {@link #getAttrsMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getAttrs();
    /**
     * <code>map&lt;string, string&gt; attrs = 6;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getAttrsMap();
    /**
     * <code>map&lt;string, string&gt; attrs = 6;</code>
     */
    /* nullable */
java.lang.String getAttrsOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; attrs = 6;</code>
     */
    java.lang.String getAttrsOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code pr.iceworld.fernando.protobuf.proto.Customer}
   */
  public static final class Customer extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pr.iceworld.fernando.protobuf.proto.Customer)
      CustomerOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Customer.newBuilder() to construct.
    private Customer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Customer() {
      name_ = "";
      gender_ = 0;
      addresses_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Customer();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pr.iceworld.fernando.protobuf.proto.CustomerProto.internal_static_pr_iceworld_fernando_protobuf_proto_Customer_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 6:
          return internalGetAttrs();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pr.iceworld.fernando.protobuf.proto.CustomerProto.internal_static_pr_iceworld_fernando_protobuf_proto_Customer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.class, pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.Builder.class);
    }

    public interface AddressOrBuilder extends
        // @@protoc_insertion_point(interface_extends:pr.iceworld.fernando.protobuf.proto.Customer.Address)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      int getId();

      /**
       * <code>string value = 2;</code>
       * @return The value.
       */
      java.lang.String getValue();
      /**
       * <code>string value = 2;</code>
       * @return The bytes for value.
       */
      com.google.protobuf.ByteString
          getValueBytes();

      /**
       * <code>bool default = 3;</code>
       * @return The default.
       */
      boolean getDefault();
    }
    /**
     * <pre>
     * embed class
     * </pre>
     *
     * Protobuf type {@code pr.iceworld.fernando.protobuf.proto.Customer.Address}
     */
    public static final class Address extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:pr.iceworld.fernando.protobuf.proto.Customer.Address)
        AddressOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Address.newBuilder() to construct.
      private Address(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Address() {
        value_ = "";
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new Address();
      }

      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pr.iceworld.fernando.protobuf.proto.CustomerProto.internal_static_pr_iceworld_fernando_protobuf_proto_Customer_Address_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pr.iceworld.fernando.protobuf.proto.CustomerProto.internal_static_pr_iceworld_fernando_protobuf_proto_Customer_Address_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.Address.class, pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.Address.Builder.class);
      }

      public static final int ID_FIELD_NUMBER = 1;
      private int id_ = 0;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }

      public static final int VALUE_FIELD_NUMBER = 2;
      @SuppressWarnings("serial")
      private volatile java.lang.Object value_ = "";
      /**
       * <code>string value = 2;</code>
       * @return The value.
       */
      @java.lang.Override
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          value_ = s;
          return s;
        }
      }
      /**
       * <code>string value = 2;</code>
       * @return The bytes for value.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int DEFAULT_FIELD_NUMBER = 3;
      private boolean default_ = false;
      /**
       * <code>bool default = 3;</code>
       * @return The default.
       */
      @java.lang.Override
      public boolean getDefault() {
        return default_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (id_ != 0) {
          output.writeInt32(1, id_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(value_)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, value_);
        }
        if (default_ != false) {
          output.writeBool(3, default_);
        }
        getUnknownFields().writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (id_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, id_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(value_)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, value_);
        }
        if (default_ != false) {
          size += com.google.protobuf.CodedOutputStream
            .computeBoolSize(3, default_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.Address)) {
          return super.equals(obj);
        }
        pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.Address other = (pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.Address) obj;

        if (getId()
            != other.getId()) return false;
        if (!getValue()
            .equals(other.getValue())) return false;
        if (getDefault()
            != other.getDefault()) return false;
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId();
        hash = (37 * hash) + VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getValue().hashCode();
        hash = (37 * hash) + DEFAULT_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getDefault());
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.Address parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.Address parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.Address parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.Address parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.Address parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.Address parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.Address parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.Address parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.Address parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.Address parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.Address parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.Address parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.Address prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * <pre>
       * embed class
       * </pre>
       *
       * Protobuf type {@code pr.iceworld.fernando.protobuf.proto.Customer.Address}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:pr.iceworld.fernando.protobuf.proto.Customer.Address)
          pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.AddressOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return pr.iceworld.fernando.protobuf.proto.CustomerProto.internal_static_pr_iceworld_fernando_protobuf_proto_Customer_Address_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return pr.iceworld.fernando.protobuf.proto.CustomerProto.internal_static_pr_iceworld_fernando_protobuf_proto_Customer_Address_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.Address.class, pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.Address.Builder.class);
        }

        // Construct using pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.Address.newBuilder()
        private Builder() {

        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);

        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          bitField0_ = 0;
          id_ = 0;
          value_ = "";
          default_ = false;
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return pr.iceworld.fernando.protobuf.proto.CustomerProto.internal_static_pr_iceworld_fernando_protobuf_proto_Customer_Address_descriptor;
        }

        @java.lang.Override
        public pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.Address getDefaultInstanceForType() {
          return pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.Address.getDefaultInstance();
        }

        @java.lang.Override
        public pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.Address build() {
          pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.Address result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.Address buildPartial() {
          pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.Address result = new pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.Address(this);
          if (bitField0_ != 0) { buildPartial0(result); }
          onBuilt();
          return result;
        }

        private void buildPartial0(pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.Address result) {
          int from_bitField0_ = bitField0_;
          if (((from_bitField0_ & 0x00000001) != 0)) {
            result.id_ = id_;
          }
          if (((from_bitField0_ & 0x00000002) != 0)) {
            result.value_ = value_;
          }
          if (((from_bitField0_ & 0x00000004) != 0)) {
            result.default_ = default_;
          }
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.Address) {
            return mergeFrom((pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.Address)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.Address other) {
          if (other == pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.Address.getDefaultInstance()) return this;
          if (other.getId() != 0) {
            setId(other.getId());
          }
          if (!other.getValue().isEmpty()) {
            value_ = other.value_;
            bitField0_ |= 0x00000002;
            onChanged();
          }
          if (other.getDefault() != false) {
            setDefault(other.getDefault());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
          }
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                case 8: {
                  id_ = input.readInt32();
                  bitField0_ |= 0x00000001;
                  break;
                } // case 8
                case 18: {
                  value_ = input.readStringRequireUtf8();
                  bitField0_ |= 0x00000002;
                  break;
                } // case 18
                case 24: {
                  default_ = input.readBool();
                  bitField0_ |= 0x00000004;
                  break;
                } // case 24
                default: {
                  if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                    done = true; // was an endgroup tag
                  }
                  break;
                } // default:
              } // switch (tag)
            } // while (!done)
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.unwrapIOException();
          } finally {
            onChanged();
          } // finally
          return this;
        }
        private int bitField0_;

        private int id_ ;
        /**
         * <code>int32 id = 1;</code>
         * @return The id.
         */
        @java.lang.Override
        public int getId() {
          return id_;
        }
        /**
         * <code>int32 id = 1;</code>
         * @param value The id to set.
         * @return This builder for chaining.
         */
        public Builder setId(int value) {

          id_ = value;
          bitField0_ |= 0x00000001;
          onChanged();
          return this;
        }
        /**
         * <code>int32 id = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearId() {
          bitField0_ = (bitField0_ & ~0x00000001);
          id_ = 0;
          onChanged();
          return this;
        }

        private java.lang.Object value_ = "";
        /**
         * <code>string value = 2;</code>
         * @return The value.
         */
        public java.lang.String getValue() {
          java.lang.Object ref = value_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            value_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string value = 2;</code>
         * @return The bytes for value.
         */
        public com.google.protobuf.ByteString
            getValueBytes() {
          java.lang.Object ref = value_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            value_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string value = 2;</code>
         * @param value The value to set.
         * @return This builder for chaining.
         */
        public Builder setValue(
            java.lang.String value) {
          if (value == null) { throw new NullPointerException(); }
          value_ = value;
          bitField0_ |= 0x00000002;
          onChanged();
          return this;
        }
        /**
         * <code>string value = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearValue() {
          value_ = getDefaultInstance().getValue();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
          return this;
        }
        /**
         * <code>string value = 2;</code>
         * @param value The bytes for value to set.
         * @return This builder for chaining.
         */
        public Builder setValueBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) { throw new NullPointerException(); }
          checkByteStringIsUtf8(value);
          value_ = value;
          bitField0_ |= 0x00000002;
          onChanged();
          return this;
        }

        private boolean default_ ;
        /**
         * <code>bool default = 3;</code>
         * @return The default.
         */
        @java.lang.Override
        public boolean getDefault() {
          return default_;
        }
        /**
         * <code>bool default = 3;</code>
         * @param value The default to set.
         * @return This builder for chaining.
         */
        public Builder setDefault(boolean value) {

          default_ = value;
          bitField0_ |= 0x00000004;
          onChanged();
          return this;
        }
        /**
         * <code>bool default = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearDefault() {
          bitField0_ = (bitField0_ & ~0x00000004);
          default_ = false;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:pr.iceworld.fernando.protobuf.proto.Customer.Address)
      }

      // @@protoc_insertion_point(class_scope:pr.iceworld.fernando.protobuf.proto.Customer.Address)
      private static final pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.Address DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.Address();
      }

      public static pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.Address getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Address>
          PARSER = new com.google.protobuf.AbstractParser<Address>() {
        @java.lang.Override
        public Address parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

      public static com.google.protobuf.Parser<Address> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Address> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.Address getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_ = 0;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GENDER_FIELD_NUMBER = 3;
    private int gender_ = 0;
    /**
     * <pre>
     * enum type
     * </pre>
     *
     * <code>.pr.iceworld.fernando.protobuf.proto.Gender gender = 3;</code>
     * @return The enum numeric value on the wire for gender.
     */
    @java.lang.Override public int getGenderValue() {
      return gender_;
    }
    /**
     * <pre>
     * enum type
     * </pre>
     *
     * <code>.pr.iceworld.fernando.protobuf.proto.Gender gender = 3;</code>
     * @return The gender.
     */
    @java.lang.Override public pr.iceworld.fernando.protobuf.proto.CustomerProto.Gender getGender() {
      pr.iceworld.fernando.protobuf.proto.CustomerProto.Gender result = pr.iceworld.fernando.protobuf.proto.CustomerProto.Gender.forNumber(gender_);
      return result == null ? pr.iceworld.fernando.protobuf.proto.CustomerProto.Gender.UNRECOGNIZED : result;
    }

    public static final int ADDRESSES_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private java.util.List<pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.Address> addresses_;
    /**
     * <pre>
     * array
     * </pre>
     *
     * <code>repeated .pr.iceworld.fernando.protobuf.proto.Customer.Address addresses = 4;</code>
     */
    @java.lang.Override
    public java.util.List<pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.Address> getAddressesList() {
      return addresses_;
    }
    /**
     * <pre>
     * array
     * </pre>
     *
     * <code>repeated .pr.iceworld.fernando.protobuf.proto.Customer.Address addresses = 4;</code>
     */
    @java.lang.Override
    public java.util.List<? extends pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.AddressOrBuilder> 
        getAddressesOrBuilderList() {
      return addresses_;
    }
    /**
     * <pre>
     * array
     * </pre>
     *
     * <code>repeated .pr.iceworld.fernando.protobuf.proto.Customer.Address addresses = 4;</code>
     */
    @java.lang.Override
    public int getAddressesCount() {
      return addresses_.size();
    }
    /**
     * <pre>
     * array
     * </pre>
     *
     * <code>repeated .pr.iceworld.fernando.protobuf.proto.Customer.Address addresses = 4;</code>
     */
    @java.lang.Override
    public pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.Address getAddresses(int index) {
      return addresses_.get(index);
    }
    /**
     * <pre>
     * array
     * </pre>
     *
     * <code>repeated .pr.iceworld.fernando.protobuf.proto.Customer.Address addresses = 4;</code>
     */
    @java.lang.Override
    public pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.AddressOrBuilder getAddressesOrBuilder(
        int index) {
      return addresses_.get(index);
    }

    public static final int PHONE_FIELD_NUMBER = 5;
    private pr.iceworld.fernando.protobuf.proto.PhoneProto.Phone phone_;
    /**
     * <code>.pr.iceworld.fernando.protobuf.proto.Phone phone = 5;</code>
     * @return Whether the phone field is set.
     */
    @java.lang.Override
    public boolean hasPhone() {
      return phone_ != null;
    }
    /**
     * <code>.pr.iceworld.fernando.protobuf.proto.Phone phone = 5;</code>
     * @return The phone.
     */
    @java.lang.Override
    public pr.iceworld.fernando.protobuf.proto.PhoneProto.Phone getPhone() {
      return phone_ == null ? pr.iceworld.fernando.protobuf.proto.PhoneProto.Phone.getDefaultInstance() : phone_;
    }
    /**
     * <code>.pr.iceworld.fernando.protobuf.proto.Phone phone = 5;</code>
     */
    @java.lang.Override
    public pr.iceworld.fernando.protobuf.proto.PhoneProto.PhoneOrBuilder getPhoneOrBuilder() {
      return phone_ == null ? pr.iceworld.fernando.protobuf.proto.PhoneProto.Phone.getDefaultInstance() : phone_;
    }

    public static final int ATTRS_FIELD_NUMBER = 6;
    private static final class AttrsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  pr.iceworld.fernando.protobuf.proto.CustomerProto.internal_static_pr_iceworld_fernando_protobuf_proto_Customer_AttrsEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    @SuppressWarnings("serial")
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> attrs_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetAttrs() {
      if (attrs_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            AttrsDefaultEntryHolder.defaultEntry);
      }
      return attrs_;
    }
    public int getAttrsCount() {
      return internalGetAttrs().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; attrs = 6;</code>
     */
    @java.lang.Override
    public boolean containsAttrs(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetAttrs().getMap().containsKey(key);
    }
    /**
     * Use {@link #getAttrsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getAttrs() {
      return getAttrsMap();
    }
    /**
     * <code>map&lt;string, string&gt; attrs = 6;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.String> getAttrsMap() {
      return internalGetAttrs().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; attrs = 6;</code>
     */
    @java.lang.Override
    public /* nullable */
java.lang.String getAttrsOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetAttrs().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; attrs = 6;</code>
     */
    @java.lang.Override
    public java.lang.String getAttrsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetAttrs().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (gender_ != pr.iceworld.fernando.protobuf.proto.CustomerProto.Gender.MALE.getNumber()) {
        output.writeEnum(3, gender_);
      }
      for (int i = 0; i < addresses_.size(); i++) {
        output.writeMessage(4, addresses_.get(i));
      }
      if (phone_ != null) {
        output.writeMessage(5, getPhone());
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetAttrs(),
          AttrsDefaultEntryHolder.defaultEntry,
          6);
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (gender_ != pr.iceworld.fernando.protobuf.proto.CustomerProto.Gender.MALE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, gender_);
      }
      for (int i = 0; i < addresses_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, addresses_.get(i));
      }
      if (phone_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getPhone());
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetAttrs().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        attrs__ = AttrsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(6, attrs__);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer)) {
        return super.equals(obj);
      }
      pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer other = (pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer) obj;

      if (getId()
          != other.getId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (gender_ != other.gender_) return false;
      if (!getAddressesList()
          .equals(other.getAddressesList())) return false;
      if (hasPhone() != other.hasPhone()) return false;
      if (hasPhone()) {
        if (!getPhone()
            .equals(other.getPhone())) return false;
      }
      if (!internalGetAttrs().equals(
          other.internalGetAttrs())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + GENDER_FIELD_NUMBER;
      hash = (53 * hash) + gender_;
      if (getAddressesCount() > 0) {
        hash = (37 * hash) + ADDRESSES_FIELD_NUMBER;
        hash = (53 * hash) + getAddressesList().hashCode();
      }
      if (hasPhone()) {
        hash = (37 * hash) + PHONE_FIELD_NUMBER;
        hash = (53 * hash) + getPhone().hashCode();
      }
      if (!internalGetAttrs().getMap().isEmpty()) {
        hash = (37 * hash) + ATTRS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetAttrs().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pr.iceworld.fernando.protobuf.proto.Customer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pr.iceworld.fernando.protobuf.proto.Customer)
        pr.iceworld.fernando.protobuf.proto.CustomerProto.CustomerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pr.iceworld.fernando.protobuf.proto.CustomerProto.internal_static_pr_iceworld_fernando_protobuf_proto_Customer_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 6:
            return internalGetAttrs();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 6:
            return internalGetMutableAttrs();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pr.iceworld.fernando.protobuf.proto.CustomerProto.internal_static_pr_iceworld_fernando_protobuf_proto_Customer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.class, pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.Builder.class);
      }

      // Construct using pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0;
        name_ = "";
        gender_ = 0;
        if (addressesBuilder_ == null) {
          addresses_ = java.util.Collections.emptyList();
        } else {
          addresses_ = null;
          addressesBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        phone_ = null;
        if (phoneBuilder_ != null) {
          phoneBuilder_.dispose();
          phoneBuilder_ = null;
        }
        internalGetMutableAttrs().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pr.iceworld.fernando.protobuf.proto.CustomerProto.internal_static_pr_iceworld_fernando_protobuf_proto_Customer_descriptor;
      }

      @java.lang.Override
      public pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer getDefaultInstanceForType() {
        return pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.getDefaultInstance();
      }

      @java.lang.Override
      public pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer build() {
        pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer buildPartial() {
        pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer result = new pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer result) {
        if (addressesBuilder_ == null) {
          if (((bitField0_ & 0x00000008) != 0)) {
            addresses_ = java.util.Collections.unmodifiableList(addresses_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.addresses_ = addresses_;
        } else {
          result.addresses_ = addressesBuilder_.build();
        }
      }

      private void buildPartial0(pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.gender_ = gender_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.phone_ = phoneBuilder_ == null
              ? phone_
              : phoneBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.attrs_ = internalGetAttrs();
          result.attrs_.makeImmutable();
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer) {
          return mergeFrom((pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer other) {
        if (other == pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.gender_ != 0) {
          setGenderValue(other.getGenderValue());
        }
        if (addressesBuilder_ == null) {
          if (!other.addresses_.isEmpty()) {
            if (addresses_.isEmpty()) {
              addresses_ = other.addresses_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureAddressesIsMutable();
              addresses_.addAll(other.addresses_);
            }
            onChanged();
          }
        } else {
          if (!other.addresses_.isEmpty()) {
            if (addressesBuilder_.isEmpty()) {
              addressesBuilder_.dispose();
              addressesBuilder_ = null;
              addresses_ = other.addresses_;
              bitField0_ = (bitField0_ & ~0x00000008);
              addressesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getAddressesFieldBuilder() : null;
            } else {
              addressesBuilder_.addAllMessages(other.addresses_);
            }
          }
        }
        if (other.hasPhone()) {
          mergePhone(other.getPhone());
        }
        internalGetMutableAttrs().mergeFrom(
            other.internalGetAttrs());
        bitField0_ |= 0x00000020;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                gender_ = input.readEnum();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 34: {
                pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.Address m =
                    input.readMessage(
                        pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.Address.parser(),
                        extensionRegistry);
                if (addressesBuilder_ == null) {
                  ensureAddressesIsMutable();
                  addresses_.add(m);
                } else {
                  addressesBuilder_.addMessage(m);
                }
                break;
              } // case 34
              case 42: {
                input.readMessage(
                    getPhoneFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 50: {
                com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
                attrs__ = input.readMessage(
                    AttrsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                internalGetMutableAttrs().getMutableMap().put(
                    attrs__.getKey(), attrs__.getValue());
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private int gender_ = 0;
      /**
       * <pre>
       * enum type
       * </pre>
       *
       * <code>.pr.iceworld.fernando.protobuf.proto.Gender gender = 3;</code>
       * @return The enum numeric value on the wire for gender.
       */
      @java.lang.Override public int getGenderValue() {
        return gender_;
      }
      /**
       * <pre>
       * enum type
       * </pre>
       *
       * <code>.pr.iceworld.fernando.protobuf.proto.Gender gender = 3;</code>
       * @param value The enum numeric value on the wire for gender to set.
       * @return This builder for chaining.
       */
      public Builder setGenderValue(int value) {
        gender_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * enum type
       * </pre>
       *
       * <code>.pr.iceworld.fernando.protobuf.proto.Gender gender = 3;</code>
       * @return The gender.
       */
      @java.lang.Override
      public pr.iceworld.fernando.protobuf.proto.CustomerProto.Gender getGender() {
        pr.iceworld.fernando.protobuf.proto.CustomerProto.Gender result = pr.iceworld.fernando.protobuf.proto.CustomerProto.Gender.forNumber(gender_);
        return result == null ? pr.iceworld.fernando.protobuf.proto.CustomerProto.Gender.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * enum type
       * </pre>
       *
       * <code>.pr.iceworld.fernando.protobuf.proto.Gender gender = 3;</code>
       * @param value The gender to set.
       * @return This builder for chaining.
       */
      public Builder setGender(pr.iceworld.fernando.protobuf.proto.CustomerProto.Gender value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        gender_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * enum type
       * </pre>
       *
       * <code>.pr.iceworld.fernando.protobuf.proto.Gender gender = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearGender() {
        bitField0_ = (bitField0_ & ~0x00000004);
        gender_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.Address> addresses_ =
        java.util.Collections.emptyList();
      private void ensureAddressesIsMutable() {
        if (!((bitField0_ & 0x00000008) != 0)) {
          addresses_ = new java.util.ArrayList<pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.Address>(addresses_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.Address, pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.Address.Builder, pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.AddressOrBuilder> addressesBuilder_;

      /**
       * <pre>
       * array
       * </pre>
       *
       * <code>repeated .pr.iceworld.fernando.protobuf.proto.Customer.Address addresses = 4;</code>
       */
      public java.util.List<pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.Address> getAddressesList() {
        if (addressesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(addresses_);
        } else {
          return addressesBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * array
       * </pre>
       *
       * <code>repeated .pr.iceworld.fernando.protobuf.proto.Customer.Address addresses = 4;</code>
       */
      public int getAddressesCount() {
        if (addressesBuilder_ == null) {
          return addresses_.size();
        } else {
          return addressesBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * array
       * </pre>
       *
       * <code>repeated .pr.iceworld.fernando.protobuf.proto.Customer.Address addresses = 4;</code>
       */
      public pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.Address getAddresses(int index) {
        if (addressesBuilder_ == null) {
          return addresses_.get(index);
        } else {
          return addressesBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * array
       * </pre>
       *
       * <code>repeated .pr.iceworld.fernando.protobuf.proto.Customer.Address addresses = 4;</code>
       */
      public Builder setAddresses(
          int index, pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.Address value) {
        if (addressesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAddressesIsMutable();
          addresses_.set(index, value);
          onChanged();
        } else {
          addressesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * array
       * </pre>
       *
       * <code>repeated .pr.iceworld.fernando.protobuf.proto.Customer.Address addresses = 4;</code>
       */
      public Builder setAddresses(
          int index, pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.Address.Builder builderForValue) {
        if (addressesBuilder_ == null) {
          ensureAddressesIsMutable();
          addresses_.set(index, builderForValue.build());
          onChanged();
        } else {
          addressesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * array
       * </pre>
       *
       * <code>repeated .pr.iceworld.fernando.protobuf.proto.Customer.Address addresses = 4;</code>
       */
      public Builder addAddresses(pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.Address value) {
        if (addressesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAddressesIsMutable();
          addresses_.add(value);
          onChanged();
        } else {
          addressesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * array
       * </pre>
       *
       * <code>repeated .pr.iceworld.fernando.protobuf.proto.Customer.Address addresses = 4;</code>
       */
      public Builder addAddresses(
          int index, pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.Address value) {
        if (addressesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAddressesIsMutable();
          addresses_.add(index, value);
          onChanged();
        } else {
          addressesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * array
       * </pre>
       *
       * <code>repeated .pr.iceworld.fernando.protobuf.proto.Customer.Address addresses = 4;</code>
       */
      public Builder addAddresses(
          pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.Address.Builder builderForValue) {
        if (addressesBuilder_ == null) {
          ensureAddressesIsMutable();
          addresses_.add(builderForValue.build());
          onChanged();
        } else {
          addressesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * array
       * </pre>
       *
       * <code>repeated .pr.iceworld.fernando.protobuf.proto.Customer.Address addresses = 4;</code>
       */
      public Builder addAddresses(
          int index, pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.Address.Builder builderForValue) {
        if (addressesBuilder_ == null) {
          ensureAddressesIsMutable();
          addresses_.add(index, builderForValue.build());
          onChanged();
        } else {
          addressesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * array
       * </pre>
       *
       * <code>repeated .pr.iceworld.fernando.protobuf.proto.Customer.Address addresses = 4;</code>
       */
      public Builder addAllAddresses(
          java.lang.Iterable<? extends pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.Address> values) {
        if (addressesBuilder_ == null) {
          ensureAddressesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, addresses_);
          onChanged();
        } else {
          addressesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * array
       * </pre>
       *
       * <code>repeated .pr.iceworld.fernando.protobuf.proto.Customer.Address addresses = 4;</code>
       */
      public Builder clearAddresses() {
        if (addressesBuilder_ == null) {
          addresses_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          addressesBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * array
       * </pre>
       *
       * <code>repeated .pr.iceworld.fernando.protobuf.proto.Customer.Address addresses = 4;</code>
       */
      public Builder removeAddresses(int index) {
        if (addressesBuilder_ == null) {
          ensureAddressesIsMutable();
          addresses_.remove(index);
          onChanged();
        } else {
          addressesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * array
       * </pre>
       *
       * <code>repeated .pr.iceworld.fernando.protobuf.proto.Customer.Address addresses = 4;</code>
       */
      public pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.Address.Builder getAddressesBuilder(
          int index) {
        return getAddressesFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * array
       * </pre>
       *
       * <code>repeated .pr.iceworld.fernando.protobuf.proto.Customer.Address addresses = 4;</code>
       */
      public pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.AddressOrBuilder getAddressesOrBuilder(
          int index) {
        if (addressesBuilder_ == null) {
          return addresses_.get(index);  } else {
          return addressesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * array
       * </pre>
       *
       * <code>repeated .pr.iceworld.fernando.protobuf.proto.Customer.Address addresses = 4;</code>
       */
      public java.util.List<? extends pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.AddressOrBuilder> 
           getAddressesOrBuilderList() {
        if (addressesBuilder_ != null) {
          return addressesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(addresses_);
        }
      }
      /**
       * <pre>
       * array
       * </pre>
       *
       * <code>repeated .pr.iceworld.fernando.protobuf.proto.Customer.Address addresses = 4;</code>
       */
      public pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.Address.Builder addAddressesBuilder() {
        return getAddressesFieldBuilder().addBuilder(
            pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.Address.getDefaultInstance());
      }
      /**
       * <pre>
       * array
       * </pre>
       *
       * <code>repeated .pr.iceworld.fernando.protobuf.proto.Customer.Address addresses = 4;</code>
       */
      public pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.Address.Builder addAddressesBuilder(
          int index) {
        return getAddressesFieldBuilder().addBuilder(
            index, pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.Address.getDefaultInstance());
      }
      /**
       * <pre>
       * array
       * </pre>
       *
       * <code>repeated .pr.iceworld.fernando.protobuf.proto.Customer.Address addresses = 4;</code>
       */
      public java.util.List<pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.Address.Builder> 
           getAddressesBuilderList() {
        return getAddressesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.Address, pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.Address.Builder, pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.AddressOrBuilder> 
          getAddressesFieldBuilder() {
        if (addressesBuilder_ == null) {
          addressesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.Address, pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.Address.Builder, pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer.AddressOrBuilder>(
                  addresses_,
                  ((bitField0_ & 0x00000008) != 0),
                  getParentForChildren(),
                  isClean());
          addresses_ = null;
        }
        return addressesBuilder_;
      }

      private pr.iceworld.fernando.protobuf.proto.PhoneProto.Phone phone_;
      private com.google.protobuf.SingleFieldBuilderV3<
          pr.iceworld.fernando.protobuf.proto.PhoneProto.Phone, pr.iceworld.fernando.protobuf.proto.PhoneProto.Phone.Builder, pr.iceworld.fernando.protobuf.proto.PhoneProto.PhoneOrBuilder> phoneBuilder_;
      /**
       * <code>.pr.iceworld.fernando.protobuf.proto.Phone phone = 5;</code>
       * @return Whether the phone field is set.
       */
      public boolean hasPhone() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>.pr.iceworld.fernando.protobuf.proto.Phone phone = 5;</code>
       * @return The phone.
       */
      public pr.iceworld.fernando.protobuf.proto.PhoneProto.Phone getPhone() {
        if (phoneBuilder_ == null) {
          return phone_ == null ? pr.iceworld.fernando.protobuf.proto.PhoneProto.Phone.getDefaultInstance() : phone_;
        } else {
          return phoneBuilder_.getMessage();
        }
      }
      /**
       * <code>.pr.iceworld.fernando.protobuf.proto.Phone phone = 5;</code>
       */
      public Builder setPhone(pr.iceworld.fernando.protobuf.proto.PhoneProto.Phone value) {
        if (phoneBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          phone_ = value;
        } else {
          phoneBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>.pr.iceworld.fernando.protobuf.proto.Phone phone = 5;</code>
       */
      public Builder setPhone(
          pr.iceworld.fernando.protobuf.proto.PhoneProto.Phone.Builder builderForValue) {
        if (phoneBuilder_ == null) {
          phone_ = builderForValue.build();
        } else {
          phoneBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>.pr.iceworld.fernando.protobuf.proto.Phone phone = 5;</code>
       */
      public Builder mergePhone(pr.iceworld.fernando.protobuf.proto.PhoneProto.Phone value) {
        if (phoneBuilder_ == null) {
          if (((bitField0_ & 0x00000010) != 0) &&
            phone_ != null &&
            phone_ != pr.iceworld.fernando.protobuf.proto.PhoneProto.Phone.getDefaultInstance()) {
            getPhoneBuilder().mergeFrom(value);
          } else {
            phone_ = value;
          }
        } else {
          phoneBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>.pr.iceworld.fernando.protobuf.proto.Phone phone = 5;</code>
       */
      public Builder clearPhone() {
        bitField0_ = (bitField0_ & ~0x00000010);
        phone_ = null;
        if (phoneBuilder_ != null) {
          phoneBuilder_.dispose();
          phoneBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.pr.iceworld.fernando.protobuf.proto.Phone phone = 5;</code>
       */
      public pr.iceworld.fernando.protobuf.proto.PhoneProto.Phone.Builder getPhoneBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getPhoneFieldBuilder().getBuilder();
      }
      /**
       * <code>.pr.iceworld.fernando.protobuf.proto.Phone phone = 5;</code>
       */
      public pr.iceworld.fernando.protobuf.proto.PhoneProto.PhoneOrBuilder getPhoneOrBuilder() {
        if (phoneBuilder_ != null) {
          return phoneBuilder_.getMessageOrBuilder();
        } else {
          return phone_ == null ?
              pr.iceworld.fernando.protobuf.proto.PhoneProto.Phone.getDefaultInstance() : phone_;
        }
      }
      /**
       * <code>.pr.iceworld.fernando.protobuf.proto.Phone phone = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          pr.iceworld.fernando.protobuf.proto.PhoneProto.Phone, pr.iceworld.fernando.protobuf.proto.PhoneProto.Phone.Builder, pr.iceworld.fernando.protobuf.proto.PhoneProto.PhoneOrBuilder> 
          getPhoneFieldBuilder() {
        if (phoneBuilder_ == null) {
          phoneBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              pr.iceworld.fernando.protobuf.proto.PhoneProto.Phone, pr.iceworld.fernando.protobuf.proto.PhoneProto.Phone.Builder, pr.iceworld.fernando.protobuf.proto.PhoneProto.PhoneOrBuilder>(
                  getPhone(),
                  getParentForChildren(),
                  isClean());
          phone_ = null;
        }
        return phoneBuilder_;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> attrs_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
          internalGetAttrs() {
        if (attrs_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              AttrsDefaultEntryHolder.defaultEntry);
        }
        return attrs_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
          internalGetMutableAttrs() {
        if (attrs_ == null) {
          attrs_ = com.google.protobuf.MapField.newMapField(
              AttrsDefaultEntryHolder.defaultEntry);
        }
        if (!attrs_.isMutable()) {
          attrs_ = attrs_.copy();
        }
        bitField0_ |= 0x00000020;
        onChanged();
        return attrs_;
      }
      public int getAttrsCount() {
        return internalGetAttrs().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; attrs = 6;</code>
       */
      @java.lang.Override
      public boolean containsAttrs(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        return internalGetAttrs().getMap().containsKey(key);
      }
      /**
       * Use {@link #getAttrsMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getAttrs() {
        return getAttrsMap();
      }
      /**
       * <code>map&lt;string, string&gt; attrs = 6;</code>
       */
      @java.lang.Override
      public java.util.Map<java.lang.String, java.lang.String> getAttrsMap() {
        return internalGetAttrs().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; attrs = 6;</code>
       */
      @java.lang.Override
      public /* nullable */
java.lang.String getAttrsOrDefault(
          java.lang.String key,
          /* nullable */
java.lang.String defaultValue) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetAttrs().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; attrs = 6;</code>
       */
      @java.lang.Override
      public java.lang.String getAttrsOrThrow(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetAttrs().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }
      public Builder clearAttrs() {
        bitField0_ = (bitField0_ & ~0x00000020);
        internalGetMutableAttrs().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; attrs = 6;</code>
       */
      public Builder removeAttrs(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        internalGetMutableAttrs().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
          getMutableAttrs() {
        bitField0_ |= 0x00000020;
        return internalGetMutableAttrs().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; attrs = 6;</code>
       */
      public Builder putAttrs(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new NullPointerException("map key"); }
        if (value == null) { throw new NullPointerException("map value"); }
        internalGetMutableAttrs().getMutableMap()
            .put(key, value);
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; attrs = 6;</code>
       */
      public Builder putAllAttrs(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableAttrs().getMutableMap()
            .putAll(values);
        bitField0_ |= 0x00000020;
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pr.iceworld.fernando.protobuf.proto.Customer)
    }

    // @@protoc_insertion_point(class_scope:pr.iceworld.fernando.protobuf.proto.Customer)
    private static final pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer();
    }

    public static pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Customer>
        PARSER = new com.google.protobuf.AbstractParser<Customer>() {
      @java.lang.Override
      public Customer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Customer> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Customer> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public pr.iceworld.fernando.protobuf.proto.CustomerProto.Customer getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pr_iceworld_fernando_protobuf_proto_Customer_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pr_iceworld_fernando_protobuf_proto_Customer_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pr_iceworld_fernando_protobuf_proto_Customer_Address_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pr_iceworld_fernando_protobuf_proto_Customer_Address_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pr_iceworld_fernando_protobuf_proto_Customer_AttrsEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pr_iceworld_fernando_protobuf_proto_Customer_AttrsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016customer.proto\022#pr.iceworld.fernando.p" +
      "rotobuf.proto\032\013phone.proto\"\224\003\n\010Customer\022" +
      "\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022;\n\006gender\030\003 \001(" +
      "\0162+.pr.iceworld.fernando.protobuf.proto." +
      "Gender\022H\n\taddresses\030\004 \003(\01325.pr.iceworld." +
      "fernando.protobuf.proto.Customer.Address" +
      "\0229\n\005phone\030\005 \001(\0132*.pr.iceworld.fernando.p" +
      "rotobuf.proto.Phone\022G\n\005attrs\030\006 \003(\01328.pr." +
      "iceworld.fernando.protobuf.proto.Custome" +
      "r.AttrsEntry\0325\n\007Address\022\n\n\002id\030\001 \001(\005\022\r\n\005v" +
      "alue\030\002 \001(\t\022\017\n\007default\030\003 \001(\010\032,\n\nAttrsEntr" +
      "y\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001*\036\n\006Gen" +
      "der\022\010\n\004MALE\020\000\022\n\n\006FEMALE\020\001B4\n#pr.iceworld" +
      ".fernando.protobuf.protoB\rCustomerProtob" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          pr.iceworld.fernando.protobuf.proto.PhoneProto.getDescriptor(),
        });
    internal_static_pr_iceworld_fernando_protobuf_proto_Customer_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pr_iceworld_fernando_protobuf_proto_Customer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pr_iceworld_fernando_protobuf_proto_Customer_descriptor,
        new java.lang.String[] { "Id", "Name", "Gender", "Addresses", "Phone", "Attrs", });
    internal_static_pr_iceworld_fernando_protobuf_proto_Customer_Address_descriptor =
      internal_static_pr_iceworld_fernando_protobuf_proto_Customer_descriptor.getNestedTypes().get(0);
    internal_static_pr_iceworld_fernando_protobuf_proto_Customer_Address_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pr_iceworld_fernando_protobuf_proto_Customer_Address_descriptor,
        new java.lang.String[] { "Id", "Value", "Default", });
    internal_static_pr_iceworld_fernando_protobuf_proto_Customer_AttrsEntry_descriptor =
      internal_static_pr_iceworld_fernando_protobuf_proto_Customer_descriptor.getNestedTypes().get(1);
    internal_static_pr_iceworld_fernando_protobuf_proto_Customer_AttrsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pr_iceworld_fernando_protobuf_proto_Customer_AttrsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    pr.iceworld.fernando.protobuf.proto.PhoneProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
