// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: phone.proto

package pr.iceworld.fernando.protobuf.proto;

public final class PhoneProto {
  private PhoneProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code pr.iceworld.fernando.protobuf.proto.Brand}
   */
  public enum Brand
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>APPLE = 0;</code>
     */
    APPLE(0),
    /**
     * <code>SAMSUNG = 1;</code>
     */
    SAMSUNG(1),
    /**
     * <code>HUAWEI = 2;</code>
     */
    HUAWEI(2),
    /**
     * <code>MI = 3;</code>
     */
    MI(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>APPLE = 0;</code>
     */
    public static final int APPLE_VALUE = 0;
    /**
     * <code>SAMSUNG = 1;</code>
     */
    public static final int SAMSUNG_VALUE = 1;
    /**
     * <code>HUAWEI = 2;</code>
     */
    public static final int HUAWEI_VALUE = 2;
    /**
     * <code>MI = 3;</code>
     */
    public static final int MI_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Brand valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Brand forNumber(int value) {
      switch (value) {
        case 0: return APPLE;
        case 1: return SAMSUNG;
        case 2: return HUAWEI;
        case 3: return MI;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Brand>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Brand> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Brand>() {
            public Brand findValueByNumber(int number) {
              return Brand.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return pr.iceworld.fernando.protobuf.proto.PhoneProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final Brand[] VALUES = values();

    public static Brand valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Brand(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:pr.iceworld.fernando.protobuf.proto.Brand)
  }

  public interface PhoneOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pr.iceworld.fernando.protobuf.proto.Phone)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string value = 2;</code>
     * @return The value.
     */
    java.lang.String getValue();
    /**
     * <code>string value = 2;</code>
     * @return The bytes for value.
     */
    com.google.protobuf.ByteString
        getValueBytes();

    /**
     * <code>.pr.iceworld.fernando.protobuf.proto.Brand brand = 3;</code>
     * @return The enum numeric value on the wire for brand.
     */
    int getBrandValue();
    /**
     * <code>.pr.iceworld.fernando.protobuf.proto.Brand brand = 3;</code>
     * @return The brand.
     */
    pr.iceworld.fernando.protobuf.proto.PhoneProto.Brand getBrand();
  }
  /**
   * Protobuf type {@code pr.iceworld.fernando.protobuf.proto.Phone}
   */
  public static final class Phone extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pr.iceworld.fernando.protobuf.proto.Phone)
      PhoneOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Phone.newBuilder() to construct.
    private Phone(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Phone() {
      value_ = "";
      brand_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Phone();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pr.iceworld.fernando.protobuf.proto.PhoneProto.internal_static_pr_iceworld_fernando_protobuf_proto_Phone_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pr.iceworld.fernando.protobuf.proto.PhoneProto.internal_static_pr_iceworld_fernando_protobuf_proto_Phone_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pr.iceworld.fernando.protobuf.proto.PhoneProto.Phone.class, pr.iceworld.fernando.protobuf.proto.PhoneProto.Phone.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_ = 0;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object value_ = "";
    /**
     * <code>string value = 2;</code>
     * @return The value.
     */
    @java.lang.Override
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        value_ = s;
        return s;
      }
    }
    /**
     * <code>string value = 2;</code>
     * @return The bytes for value.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BRAND_FIELD_NUMBER = 3;
    private int brand_ = 0;
    /**
     * <code>.pr.iceworld.fernando.protobuf.proto.Brand brand = 3;</code>
     * @return The enum numeric value on the wire for brand.
     */
    @java.lang.Override public int getBrandValue() {
      return brand_;
    }
    /**
     * <code>.pr.iceworld.fernando.protobuf.proto.Brand brand = 3;</code>
     * @return The brand.
     */
    @java.lang.Override public pr.iceworld.fernando.protobuf.proto.PhoneProto.Brand getBrand() {
      pr.iceworld.fernando.protobuf.proto.PhoneProto.Brand result = pr.iceworld.fernando.protobuf.proto.PhoneProto.Brand.forNumber(brand_);
      return result == null ? pr.iceworld.fernando.protobuf.proto.PhoneProto.Brand.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(value_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, value_);
      }
      if (brand_ != pr.iceworld.fernando.protobuf.proto.PhoneProto.Brand.APPLE.getNumber()) {
        output.writeEnum(3, brand_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(value_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, value_);
      }
      if (brand_ != pr.iceworld.fernando.protobuf.proto.PhoneProto.Brand.APPLE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, brand_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pr.iceworld.fernando.protobuf.proto.PhoneProto.Phone)) {
        return super.equals(obj);
      }
      pr.iceworld.fernando.protobuf.proto.PhoneProto.Phone other = (pr.iceworld.fernando.protobuf.proto.PhoneProto.Phone) obj;

      if (getId()
          != other.getId()) return false;
      if (!getValue()
          .equals(other.getValue())) return false;
      if (brand_ != other.brand_) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
      hash = (37 * hash) + BRAND_FIELD_NUMBER;
      hash = (53 * hash) + brand_;
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pr.iceworld.fernando.protobuf.proto.PhoneProto.Phone parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pr.iceworld.fernando.protobuf.proto.PhoneProto.Phone parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pr.iceworld.fernando.protobuf.proto.PhoneProto.Phone parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pr.iceworld.fernando.protobuf.proto.PhoneProto.Phone parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pr.iceworld.fernando.protobuf.proto.PhoneProto.Phone parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pr.iceworld.fernando.protobuf.proto.PhoneProto.Phone parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pr.iceworld.fernando.protobuf.proto.PhoneProto.Phone parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pr.iceworld.fernando.protobuf.proto.PhoneProto.Phone parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pr.iceworld.fernando.protobuf.proto.PhoneProto.Phone parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pr.iceworld.fernando.protobuf.proto.PhoneProto.Phone parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pr.iceworld.fernando.protobuf.proto.PhoneProto.Phone parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pr.iceworld.fernando.protobuf.proto.PhoneProto.Phone parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pr.iceworld.fernando.protobuf.proto.PhoneProto.Phone prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pr.iceworld.fernando.protobuf.proto.Phone}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pr.iceworld.fernando.protobuf.proto.Phone)
        pr.iceworld.fernando.protobuf.proto.PhoneProto.PhoneOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pr.iceworld.fernando.protobuf.proto.PhoneProto.internal_static_pr_iceworld_fernando_protobuf_proto_Phone_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pr.iceworld.fernando.protobuf.proto.PhoneProto.internal_static_pr_iceworld_fernando_protobuf_proto_Phone_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pr.iceworld.fernando.protobuf.proto.PhoneProto.Phone.class, pr.iceworld.fernando.protobuf.proto.PhoneProto.Phone.Builder.class);
      }

      // Construct using pr.iceworld.fernando.protobuf.proto.PhoneProto.Phone.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0;
        value_ = "";
        brand_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pr.iceworld.fernando.protobuf.proto.PhoneProto.internal_static_pr_iceworld_fernando_protobuf_proto_Phone_descriptor;
      }

      @java.lang.Override
      public pr.iceworld.fernando.protobuf.proto.PhoneProto.Phone getDefaultInstanceForType() {
        return pr.iceworld.fernando.protobuf.proto.PhoneProto.Phone.getDefaultInstance();
      }

      @java.lang.Override
      public pr.iceworld.fernando.protobuf.proto.PhoneProto.Phone build() {
        pr.iceworld.fernando.protobuf.proto.PhoneProto.Phone result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public pr.iceworld.fernando.protobuf.proto.PhoneProto.Phone buildPartial() {
        pr.iceworld.fernando.protobuf.proto.PhoneProto.Phone result = new pr.iceworld.fernando.protobuf.proto.PhoneProto.Phone(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(pr.iceworld.fernando.protobuf.proto.PhoneProto.Phone result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.value_ = value_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.brand_ = brand_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pr.iceworld.fernando.protobuf.proto.PhoneProto.Phone) {
          return mergeFrom((pr.iceworld.fernando.protobuf.proto.PhoneProto.Phone)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pr.iceworld.fernando.protobuf.proto.PhoneProto.Phone other) {
        if (other == pr.iceworld.fernando.protobuf.proto.PhoneProto.Phone.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getValue().isEmpty()) {
          value_ = other.value_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.brand_ != 0) {
          setBrandValue(other.getBrandValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                value_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                brand_ = input.readEnum();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object value_ = "";
      /**
       * <code>string value = 2;</code>
       * @return The value.
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string value = 2;</code>
       * @return The bytes for value.
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string value = 2;</code>
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        value_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string value = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        value_ = getDefaultInstance().getValue();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string value = 2;</code>
       * @param value The bytes for value to set.
       * @return This builder for chaining.
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        value_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private int brand_ = 0;
      /**
       * <code>.pr.iceworld.fernando.protobuf.proto.Brand brand = 3;</code>
       * @return The enum numeric value on the wire for brand.
       */
      @java.lang.Override public int getBrandValue() {
        return brand_;
      }
      /**
       * <code>.pr.iceworld.fernando.protobuf.proto.Brand brand = 3;</code>
       * @param value The enum numeric value on the wire for brand to set.
       * @return This builder for chaining.
       */
      public Builder setBrandValue(int value) {
        brand_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.pr.iceworld.fernando.protobuf.proto.Brand brand = 3;</code>
       * @return The brand.
       */
      @java.lang.Override
      public pr.iceworld.fernando.protobuf.proto.PhoneProto.Brand getBrand() {
        pr.iceworld.fernando.protobuf.proto.PhoneProto.Brand result = pr.iceworld.fernando.protobuf.proto.PhoneProto.Brand.forNumber(brand_);
        return result == null ? pr.iceworld.fernando.protobuf.proto.PhoneProto.Brand.UNRECOGNIZED : result;
      }
      /**
       * <code>.pr.iceworld.fernando.protobuf.proto.Brand brand = 3;</code>
       * @param value The brand to set.
       * @return This builder for chaining.
       */
      public Builder setBrand(pr.iceworld.fernando.protobuf.proto.PhoneProto.Brand value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        brand_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.pr.iceworld.fernando.protobuf.proto.Brand brand = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearBrand() {
        bitField0_ = (bitField0_ & ~0x00000004);
        brand_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pr.iceworld.fernando.protobuf.proto.Phone)
    }

    // @@protoc_insertion_point(class_scope:pr.iceworld.fernando.protobuf.proto.Phone)
    private static final pr.iceworld.fernando.protobuf.proto.PhoneProto.Phone DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pr.iceworld.fernando.protobuf.proto.PhoneProto.Phone();
    }

    public static pr.iceworld.fernando.protobuf.proto.PhoneProto.Phone getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Phone>
        PARSER = new com.google.protobuf.AbstractParser<Phone>() {
      @java.lang.Override
      public Phone parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Phone> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Phone> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public pr.iceworld.fernando.protobuf.proto.PhoneProto.Phone getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pr_iceworld_fernando_protobuf_proto_Phone_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pr_iceworld_fernando_protobuf_proto_Phone_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013phone.proto\022#pr.iceworld.fernando.prot" +
      "obuf.proto\"]\n\005Phone\022\n\n\002id\030\001 \001(\005\022\r\n\005value" +
      "\030\002 \001(\t\0229\n\005brand\030\003 \001(\0162*.pr.iceworld.fern" +
      "ando.protobuf.proto.Brand*9\n\005Brand\022\t\n\005AP" +
      "PLE\020\000\022\013\n\007SAMSUNG\020\001\022\n\n\006HUAWEI\020\002\022\006\n\002MI\020\003\"\004" +
      "\010\004\020\023B1\n#pr.iceworld.fernando.protobuf.pr" +
      "otoB\nPhoneProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_pr_iceworld_fernando_protobuf_proto_Phone_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pr_iceworld_fernando_protobuf_proto_Phone_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pr_iceworld_fernando_protobuf_proto_Phone_descriptor,
        new java.lang.String[] { "Id", "Value", "Brand", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
